//
// File generated by HDevelop for HALCON/.NET (C#) Version 24.11.1.0
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

namespace VisionMotionAlignment.Services.Vision
{

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  //Note global variables cannot be shared across exports with different namespace
  // Procedures 
  // External procedures 
  // Chapter: Develop
  // Short Description: Open a new graphics window that preserves the aspect ratio of the given image. 
  public void dev_open_window_fit_image (HObject ho_Image, HTuple hv_Row, HTuple hv_Column, 
      HTuple hv_WidthLimit, HTuple hv_HeightLimit, out HTuple hv_WindowHandle)
  {




    // Local iconic variables 

    // Local control variables 

    HTuple hv_MinWidth = new HTuple(), hv_MaxWidth = new HTuple();
    HTuple hv_MinHeight = new HTuple(), hv_MaxHeight = new HTuple();
    HTuple hv_ResizeFactor = new HTuple(), hv_ImageWidth = new HTuple();
    HTuple hv_ImageHeight = new HTuple(), hv_TempWidth = new HTuple();
    HTuple hv_TempHeight = new HTuple(), hv_WindowWidth = new HTuple();
    HTuple hv_WindowHeight = new HTuple();
    // Initialize local and output iconic variables 
    hv_WindowHandle = new HTuple();
    try
    {
      //This procedure opens a new graphics window and adjusts the size
      //such that it fits into the limits specified by WidthLimit
      //and HeightLimit, but also maintains the correct image aspect ratio.
      //
      //If it is impossible to match the minimum and maximum extent requirements
      //at the same time (f.e. if the image is very long but narrow),
      //the maximum value gets a higher priority,
      //
      //Parse input tuple WidthLimit
      if ((int)((new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(
          0))).TupleOr(new HTuple(hv_WidthLimit.TupleLess(0)))) != 0)
      {
        hv_MinWidth.Dispose();
        hv_MinWidth = 500;
        hv_MaxWidth.Dispose();
        hv_MaxWidth = 800;
      }
      else if ((int)(new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(
          1))) != 0)
      {
        hv_MinWidth.Dispose();
        hv_MinWidth = 0;
        hv_MaxWidth.Dispose();
        hv_MaxWidth = new HTuple(hv_WidthLimit);
      }
      else
      {
        hv_MinWidth.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_MinWidth = hv_WidthLimit.TupleSelect(
            0);
        }
        hv_MaxWidth.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_MaxWidth = hv_WidthLimit.TupleSelect(
            1);
        }
      }
      //Parse input tuple HeightLimit
      if ((int)((new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(
          0))).TupleOr(new HTuple(hv_HeightLimit.TupleLess(0)))) != 0)
      {
        hv_MinHeight.Dispose();
        hv_MinHeight = 400;
        hv_MaxHeight.Dispose();
        hv_MaxHeight = 600;
      }
      else if ((int)(new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(
          1))) != 0)
      {
        hv_MinHeight.Dispose();
        hv_MinHeight = 0;
        hv_MaxHeight.Dispose();
        hv_MaxHeight = new HTuple(hv_HeightLimit);
      }
      else
      {
        hv_MinHeight.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_MinHeight = hv_HeightLimit.TupleSelect(
            0);
        }
        hv_MaxHeight.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_MaxHeight = hv_HeightLimit.TupleSelect(
            1);
        }
      }
      //
      //Test, if window size has to be changed.
      hv_ResizeFactor.Dispose();
      hv_ResizeFactor = 1;
      hv_ImageWidth.Dispose();hv_ImageHeight.Dispose();
      HOperatorSet.GetImageSize(ho_Image, out hv_ImageWidth, out hv_ImageHeight);
      //First, expand window to the minimum extents (if necessary).
      if ((int)((new HTuple(hv_MinWidth.TupleGreater(hv_ImageWidth))).TupleOr(new HTuple(hv_MinHeight.TupleGreater(
          hv_ImageHeight)))) != 0)
      {
        hv_ResizeFactor.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_ResizeFactor = (((((hv_MinWidth.TupleReal()
            )/hv_ImageWidth)).TupleConcat((hv_MinHeight.TupleReal())/hv_ImageHeight))).TupleMax()
            ;
        }
      }
      hv_TempWidth.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_TempWidth = hv_ImageWidth*hv_ResizeFactor;
      }
      hv_TempHeight.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_TempHeight = hv_ImageHeight*hv_ResizeFactor;
      }
      //Then, shrink window to maximum extents (if necessary).
      if ((int)((new HTuple(hv_MaxWidth.TupleLess(hv_TempWidth))).TupleOr(new HTuple(hv_MaxHeight.TupleLess(
          hv_TempHeight)))) != 0)
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_ResizeFactor = hv_ResizeFactor*((((((hv_MaxWidth.TupleReal()
            )/hv_TempWidth)).TupleConcat((hv_MaxHeight.TupleReal())/hv_TempHeight))).TupleMin()
            );
        hv_ResizeFactor.Dispose();
        hv_ResizeFactor = ExpTmpLocalVar_ResizeFactor;
        }
        }
      }
      hv_WindowWidth.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_WindowWidth = hv_ImageWidth*hv_ResizeFactor;
      }
      hv_WindowHeight.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_WindowHeight = hv_ImageHeight*hv_ResizeFactor;
      }
      //Resize window
      HOperatorSet.SetWindowAttr("background_color","black");
      HOperatorSet.OpenWindow(hv_Row,hv_Column,hv_WindowWidth,hv_WindowHeight,0,"visible","",out hv_WindowHandle);
      HDevWindowStack.Push(hv_WindowHandle);
      if (HDevWindowStack.IsOpen())
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        HOperatorSet.SetPart(HDevWindowStack.GetActive(), 0, 0, hv_ImageHeight-1, 
            hv_ImageWidth-1);
        }
      }

      hv_MinWidth.Dispose();
      hv_MaxWidth.Dispose();
      hv_MinHeight.Dispose();
      hv_MaxHeight.Dispose();
      hv_ResizeFactor.Dispose();
      hv_ImageWidth.Dispose();
      hv_ImageHeight.Dispose();
      hv_TempWidth.Dispose();
      hv_TempHeight.Dispose();
      hv_WindowWidth.Dispose();
      hv_WindowHeight.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {

      hv_MinWidth.Dispose();
      hv_MaxWidth.Dispose();
      hv_MinHeight.Dispose();
      hv_MaxHeight.Dispose();
      hv_ResizeFactor.Dispose();
      hv_ImageWidth.Dispose();
      hv_ImageHeight.Dispose();
      hv_TempWidth.Dispose();
      hv_TempHeight.Dispose();
      hv_WindowWidth.Dispose();
      hv_WindowHeight.Dispose();

      throw HDevExpDefaultException;
    }
  }

  // Chapter: Develop
  // Short Description: Switch dev_update_pc, dev_update_var, and dev_update_window to 'off'. 
  public void dev_update_off ()
  {

    // Initialize local and output iconic variables 
    //This procedure sets different update settings to 'off'.
    //This is useful to get the best performance and reduce overhead.
    //
    // dev_update_pc(...); only in hdevelop
    // dev_update_var(...); only in hdevelop
    // dev_update_window(...); only in hdevelop


    return;
  }

  // Chapter: Graphics / Text
  // Short Description: Display 'Click 'Run' to continue' in the lower right corner of the screen. 
  public void disp_continue_message (HTuple hv_WindowHandle, HTuple hv_Color, HTuple hv_Box)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_GenParamName = new HTuple(), hv_GenParamValue = new HTuple();
    HTuple hv_ContinueMessage = new HTuple();
    HTuple   hv_Color_COPY_INP_TMP = new HTuple(hv_Color);

    // Initialize local and output iconic variables 
    try
    {
      //This procedure displays 'Press Run (F5) to continue' in the
      //lower right corner of the screen.
      //It uses the procedure disp_message.
      //
      //Input parameters:
      //WindowHandle: The window, where the text shall be displayed
      //Color: defines the text color.
      //   If set to '' or 'auto', the currently set color is used.
      //Box: If set to 'true', the text is displayed in a box.
      //
      //Convert the parameter Box to generic parameters.
      hv_GenParamName.Dispose();
      hv_GenParamName = new HTuple();
      hv_GenParamValue.Dispose();
      hv_GenParamValue = new HTuple();
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(0))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleEqual("false"))) != 0)
        {
          //Display no box
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(0));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(1))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleEqual("false"))) != 0)
        {
          //Display no shadow.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a shadow color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(1));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      //
      if ((int)(new HTuple(hv_Color_COPY_INP_TMP.TupleEqual(""))) != 0)
      {
        //disp_text does not accept an empty string for Color.
        hv_Color_COPY_INP_TMP.Dispose();
        hv_Color_COPY_INP_TMP = new HTuple();
      }
      //
      //Display the message.
      hv_ContinueMessage.Dispose();
      hv_ContinueMessage = "Press Run (F5) to continue";
      HOperatorSet.DispText(hv_WindowHandle, hv_ContinueMessage, "window", "bottom", 
          "right", hv_Color_COPY_INP_TMP, hv_GenParamName, hv_GenParamValue);

      hv_Color_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();
      hv_ContinueMessage.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {

      hv_Color_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();
      hv_ContinueMessage.Dispose();

      throw HDevExpDefaultException;
    }
  }

  // Chapter: Graphics / Text
  // Short Description: Write one or multiple text messages. 
  public void disp_message (HTuple hv_WindowHandle, HTuple hv_String, HTuple hv_CoordSystem, 
      HTuple hv_Row, HTuple hv_Column, HTuple hv_Color, HTuple hv_Box)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_GenParamName = new HTuple(), hv_GenParamValue = new HTuple();
    HTuple   hv_Color_COPY_INP_TMP = new HTuple(hv_Color);
    HTuple   hv_Column_COPY_INP_TMP = new HTuple(hv_Column);
    HTuple   hv_CoordSystem_COPY_INP_TMP = new HTuple(hv_CoordSystem);
    HTuple   hv_Row_COPY_INP_TMP = new HTuple(hv_Row);

    // Initialize local and output iconic variables 
    try
    {
      //This procedure displays text in a graphics window.
      //
      //Input parameters:
      //WindowHandle: The WindowHandle of the graphics window, where
      //   the message should be displayed.
      //String: A tuple of strings containing the text messages to be displayed.
      //CoordSystem: If set to 'window', the text position is given
      //   with respect to the window coordinate system.
      //   If set to 'image', image coordinates are used.
      //   (This may be useful in zoomed images.)
      //Row: The row coordinate of the desired text position.
      //   You can pass a single value or a tuple of values.
      //   See the explanation below.
      //   Default: 12.
      //Column: The column coordinate of the desired text position.
      //   You can pass a single value or a tuple of values.
      //   See the explanation below.
      //   Default: 12.
      //Color: defines the color of the text as string.
      //   If set to [] or '' the currently set color is used.
      //   If a tuple of strings is passed, the colors are used cyclically
      //   for every text position defined by Row and Column,
      //   or every new text line in case of |Row| == |Column| == 1.
      //Box: A tuple controlling a possible box surrounding the text.
      //   Its entries:
      //   - Box[0]: Controls the box and its color. Possible values:
      //     -- 'true' (Default): An orange box is displayed.
      //     -- 'false': No box is displayed.
      //     -- color string: A box is displayed in the given color, e.g., 'white', '#FF00CC'.
      //   - Box[1] (Optional): Controls the shadow of the box. Possible values:
      //     -- 'true' (Default): A shadow is displayed in
      //               darker orange if Box[0] is not a color and in 'white' otherwise.
      //     -- 'false': No shadow is displayed.
      //     -- color string: A shadow is displayed in the given color, e.g., 'white', '#FF00CC'.
      //
      //It is possible to display multiple text strings in a single call.
      //In this case, some restrictions apply on the
      //parameters String, Row, and Column:
      //They can only have either 1 entry or n entries.
      //Behavior in the different cases:
      //   - Multiple text positions are specified, i.e.,
      //       - |Row| == n, |Column| == n
      //       - |Row| == n, |Column| == 1
      //       - |Row| == 1, |Column| == n
      //     In this case we distinguish:
      //       - |String| == n: Each element of String is displayed
      //                        at the corresponding position.
      //       - |String| == 1: String is displayed n times
      //                        at the corresponding positions.
      //   - Exactly one text position is specified,
      //      i.e., |Row| == |Column| == 1:
      //      Each element of String is display in a new textline.
      //
      //
      //Convert the parameters for disp_text.
      if ((int)((new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(new HTuple()))).TupleOr(
          new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(new HTuple())))) != 0)
      {

        hv_Color_COPY_INP_TMP.Dispose();
        hv_Column_COPY_INP_TMP.Dispose();
        hv_CoordSystem_COPY_INP_TMP.Dispose();
        hv_Row_COPY_INP_TMP.Dispose();
        hv_GenParamName.Dispose();
        hv_GenParamValue.Dispose();

        return;
      }
      if ((int)(new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(-1))) != 0)
      {
        hv_Row_COPY_INP_TMP.Dispose();
        hv_Row_COPY_INP_TMP = 12;
      }
      if ((int)(new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(-1))) != 0)
      {
        hv_Column_COPY_INP_TMP.Dispose();
        hv_Column_COPY_INP_TMP = 12;
      }
      //
      //Convert the parameter Box to generic parameters.
      hv_GenParamName.Dispose();
      hv_GenParamName = new HTuple();
      hv_GenParamValue.Dispose();
      hv_GenParamValue = new HTuple();
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(0))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleEqual("false"))) != 0)
        {
          //Display no box
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(0));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(1))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleEqual("false"))) != 0)
        {
          //Display no shadow.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a shadow color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(1));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      //Restore default CoordSystem behavior.
      if ((int)(new HTuple(hv_CoordSystem_COPY_INP_TMP.TupleNotEqual("window"))) != 0)
      {
        hv_CoordSystem_COPY_INP_TMP.Dispose();
        hv_CoordSystem_COPY_INP_TMP = "image";
      }
      //
      if ((int)(new HTuple(hv_Color_COPY_INP_TMP.TupleEqual(""))) != 0)
      {
        //disp_text does not accept an empty string for Color.
        hv_Color_COPY_INP_TMP.Dispose();
        hv_Color_COPY_INP_TMP = new HTuple();
      }
      //
      HOperatorSet.DispText(hv_WindowHandle, hv_String, hv_CoordSystem_COPY_INP_TMP, 
          hv_Row_COPY_INP_TMP, hv_Column_COPY_INP_TMP, hv_Color_COPY_INP_TMP, hv_GenParamName, 
          hv_GenParamValue);

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      throw HDevExpDefaultException;
    }
  }

  // Chapter: Graphics / Text
  // Short Description: Set font independent of OS 
  public void set_display_font (HTuple hv_WindowHandle, HTuple hv_Size, HTuple hv_Font, 
      HTuple hv_Bold, HTuple hv_Slant)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_OS = new HTuple(), hv_Fonts = new HTuple();
    HTuple hv_Style = new HTuple(), hv_Exception = new HTuple();
    HTuple hv_AvailableFonts = new HTuple(), hv_Fdx = new HTuple();
    HTuple hv_Indices = new HTuple();
    HTuple   hv_Font_COPY_INP_TMP = new HTuple(hv_Font);
    HTuple   hv_Size_COPY_INP_TMP = new HTuple(hv_Size);

    // Initialize local and output iconic variables 
    try
    {
      //This procedure sets the text font of the current window with
      //the specified attributes.
      //
      //Input parameters:
      //WindowHandle: The graphics window for which the font will be set
      //Size: The font size. If Size=-1, the default of 16 is used.
      //Bold: If set to 'true', a bold font is used
      //Slant: If set to 'true', a slanted font is used
      //
      hv_OS.Dispose();
      HOperatorSet.GetSystem("operating_system", out hv_OS);
      if ((int)((new HTuple(hv_Size_COPY_INP_TMP.TupleEqual(new HTuple()))).TupleOr(
          new HTuple(hv_Size_COPY_INP_TMP.TupleEqual(-1)))) != 0)
      {
        hv_Size_COPY_INP_TMP.Dispose();
        hv_Size_COPY_INP_TMP = 16;
      }
      if ((int)(new HTuple(((hv_OS.TupleSubstr(0,2))).TupleEqual("Win"))) != 0)
      {
        //Restore previous behavior
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Size = ((1.13677*hv_Size_COPY_INP_TMP)).TupleInt()
            ;
        hv_Size_COPY_INP_TMP.Dispose();
        hv_Size_COPY_INP_TMP = ExpTmpLocalVar_Size;
        }
        }
      }
      else
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Size = hv_Size_COPY_INP_TMP.TupleInt()
            ;
        hv_Size_COPY_INP_TMP.Dispose();
        hv_Size_COPY_INP_TMP = ExpTmpLocalVar_Size;
        }
        }
      }
      if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("Courier"))) != 0)
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Courier";
        hv_Fonts[1] = "Courier 10 Pitch";
        hv_Fonts[2] = "Courier New";
        hv_Fonts[3] = "CourierNew";
        hv_Fonts[4] = "Liberation Mono";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("mono"))) != 0)
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Consolas";
        hv_Fonts[1] = "Menlo";
        hv_Fonts[2] = "Courier";
        hv_Fonts[3] = "Courier 10 Pitch";
        hv_Fonts[4] = "FreeMono";
        hv_Fonts[5] = "Liberation Mono";
        hv_Fonts[6] = "DejaVu Sans Mono";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("sans"))) != 0)
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Luxi Sans";
        hv_Fonts[1] = "DejaVu Sans";
        hv_Fonts[2] = "FreeSans";
        hv_Fonts[3] = "Arial";
        hv_Fonts[4] = "Liberation Sans";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("serif"))) != 0)
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Times New Roman";
        hv_Fonts[1] = "Luxi Serif";
        hv_Fonts[2] = "DejaVu Serif";
        hv_Fonts[3] = "FreeSerif";
        hv_Fonts[4] = "Utopia";
        hv_Fonts[5] = "Liberation Serif";
      }
      else
      {
        hv_Fonts.Dispose();
        hv_Fonts = new HTuple(hv_Font_COPY_INP_TMP);
      }
      hv_Style.Dispose();
      hv_Style = "";
      if ((int)(new HTuple(hv_Bold.TupleEqual("true"))) != 0)
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Style = hv_Style+"Bold";
        hv_Style.Dispose();
        hv_Style = ExpTmpLocalVar_Style;
        }
        }
      }
      else if ((int)(new HTuple(hv_Bold.TupleNotEqual("false"))) != 0)
      {
        hv_Exception.Dispose();
        hv_Exception = "Wrong value of control parameter Bold";
        throw new HalconException(hv_Exception);
      }
      if ((int)(new HTuple(hv_Slant.TupleEqual("true"))) != 0)
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Style = hv_Style+"Italic";
        hv_Style.Dispose();
        hv_Style = ExpTmpLocalVar_Style;
        }
        }
      }
      else if ((int)(new HTuple(hv_Slant.TupleNotEqual("false"))) != 0)
      {
        hv_Exception.Dispose();
        hv_Exception = "Wrong value of control parameter Slant";
        throw new HalconException(hv_Exception);
      }
      if ((int)(new HTuple(hv_Style.TupleEqual(""))) != 0)
      {
        hv_Style.Dispose();
        hv_Style = "Normal";
      }
      hv_AvailableFonts.Dispose();
      HOperatorSet.QueryFont(hv_WindowHandle, out hv_AvailableFonts);
      hv_Font_COPY_INP_TMP.Dispose();
      hv_Font_COPY_INP_TMP = "";
      for (hv_Fdx=0; (int)hv_Fdx<=(int)((new HTuple(hv_Fonts.TupleLength()))-1); hv_Fdx = (int)hv_Fdx + 1)
      {
        hv_Indices.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_Indices = hv_AvailableFonts.TupleFind(
            hv_Fonts.TupleSelect(hv_Fdx));
        }
        if ((int)(new HTuple((new HTuple(hv_Indices.TupleLength())).TupleGreater(
            0))) != 0)
        {
          if ((int)(new HTuple(((hv_Indices.TupleSelect(0))).TupleGreaterEqual(0))) != 0)
          {
            hv_Font_COPY_INP_TMP.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
            hv_Font_COPY_INP_TMP = hv_Fonts.TupleSelect(
                hv_Fdx);
            }
            break;
          }
        }
      }
      if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual(""))) != 0)
      {
        throw new HalconException("Wrong value of control parameter Font");
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      {
      HTuple 
        ExpTmpLocalVar_Font = (((hv_Font_COPY_INP_TMP+"-")+hv_Style)+"-")+hv_Size_COPY_INP_TMP;
      hv_Font_COPY_INP_TMP.Dispose();
      hv_Font_COPY_INP_TMP = ExpTmpLocalVar_Font;
      }
      }
      HOperatorSet.SetFont(hv_WindowHandle, hv_Font_COPY_INP_TMP);

      hv_Font_COPY_INP_TMP.Dispose();
      hv_Size_COPY_INP_TMP.Dispose();
      hv_OS.Dispose();
      hv_Fonts.Dispose();
      hv_Style.Dispose();
      hv_Exception.Dispose();
      hv_AvailableFonts.Dispose();
      hv_Fdx.Dispose();
      hv_Indices.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {

      hv_Font_COPY_INP_TMP.Dispose();
      hv_Size_COPY_INP_TMP.Dispose();
      hv_OS.Dispose();
      hv_Fonts.Dispose();
      hv_Style.Dispose();
      hv_Exception.Dispose();
      hv_AvailableFonts.Dispose();
      hv_Fdx.Dispose();
      hv_Indices.Dispose();

      throw HDevExpDefaultException;
    }
  }

  // Local procedures 
  public void display_results (HObject ho_ImageAffineTrans, HObject ho_LeftOvers, 
      HObject ho_FinalClasses, HObject ho_WrongPills, HTuple hv_CountFinalClass, HTuple hv_PillTypeCount, 
      HTuple hv_WindowHandle)
  {




    // Local iconic variables 

    HObject ho_RedLeftOvers, ho_ObjectSelected;

    // Local control variables 

    HTuple hv_ThereWereErrors = new HTuple(), hv_PillType = new HTuple();
    HTuple hv_Numbers = new HTuple(), hv_Message = new HTuple();
    HTuple hv_Errors = new HTuple(), hv_Colors = new HTuple();
    HTuple hv_NumWrong = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_RedLeftOvers);
    HOperatorSet.GenEmptyObj(out ho_ObjectSelected);
    try
    {
      hv_ThereWereErrors.Dispose();
      hv_ThereWereErrors = 0;
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.DispObj(ho_ImageAffineTrans, HDevWindowStack.GetActive());
      }
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetDraw(HDevWindowStack.GetActive(), "margin");
      }
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetLineWidth(HDevWindowStack.GetActive(), 4);
      }
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetColor(HDevWindowStack.GetActive(), "red");
      }
      ho_RedLeftOvers.Dispose();
      HOperatorSet.DilationCircle(ho_LeftOvers, out ho_RedLeftOvers, 2.5);
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.DispObj(ho_RedLeftOvers, HDevWindowStack.GetActive());
      }
      //
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetLineWidth(HDevWindowStack.GetActive(), 3);
      }
      ho_ObjectSelected.Dispose();
      HOperatorSet.SelectObj(ho_FinalClasses, out ho_ObjectSelected, 1);
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetColor(HDevWindowStack.GetActive(), "goldenrod");
      }
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.DispObj(ho_ObjectSelected, HDevWindowStack.GetActive());
      }
      ho_ObjectSelected.Dispose();
      HOperatorSet.SelectObj(ho_FinalClasses, out ho_ObjectSelected, 3);
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetColor(HDevWindowStack.GetActive(), "medium forest green");
      }
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.DispObj(ho_ObjectSelected, HDevWindowStack.GetActive());
      }
      ho_ObjectSelected.Dispose();
      HOperatorSet.SelectObj(ho_FinalClasses, out ho_ObjectSelected, 2);
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetColor(HDevWindowStack.GetActive(), "firebrick");
      }
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.DispObj(ho_ObjectSelected, HDevWindowStack.GetActive());
      }
      //
      hv_PillType.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_PillType = ((
          (new HTuple("\"yellow\"")).TupleConcat("\"red\"")).TupleConcat("\"green\"")).TupleString(
          "-8");
      }
      hv_Numbers.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_Numbers = (("# Pill type "+hv_PillType)+": ")+hv_CountFinalClass;
      }
      hv_Message.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_Message = ("# Pill type "+hv_PillType)+": ";
      }
      hv_Errors.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_Errors = ((hv_CountFinalClass.TupleNotEqualElem(
          hv_PillTypeCount))).TupleString("1");
      }
      hv_Colors.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_Colors = hv_Errors.TupleRegexpReplace(
          "0","black");
      }
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      {
      HTuple 
        ExpTmpLocalVar_Colors = hv_Colors.TupleRegexpReplace(
          "1","red");
      hv_Colors.Dispose();
      hv_Colors = ExpTmpLocalVar_Colors;
      }
      }
      //
      disp_message(hv_WindowHandle, hv_Numbers, "window", 10, 10, hv_Colors, "true");
      //
      hv_NumWrong.Dispose();
      HOperatorSet.CountObj(ho_WrongPills, out hv_NumWrong);
      if ((int)(new HTuple(hv_NumWrong.TupleGreater(0))) != 0)
      {
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        disp_message(hv_WindowHandle, "# Wrong pill type   : "+hv_NumWrong, "window", 
            10+60, 10, "red", "true");
        }
      }
      if ((int)(new HTuple(((hv_Errors.TupleFind("1"))).TupleNotEqual(-1))) != 0)
      {
        disp_message(hv_WindowHandle, "Not OK", "window", 10, 600, "red", "true");
      }
      else
      {
        disp_message(hv_WindowHandle, "OK", "window", 10, 600, "forest green", "true");
      }
      ho_RedLeftOvers.Dispose();
      ho_ObjectSelected.Dispose();

      hv_ThereWereErrors.Dispose();
      hv_PillType.Dispose();
      hv_Numbers.Dispose();
      hv_Message.Dispose();
      hv_Errors.Dispose();
      hv_Colors.Dispose();
      hv_NumWrong.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_RedLeftOvers.Dispose();
      ho_ObjectSelected.Dispose();

      hv_ThereWereErrors.Dispose();
      hv_PillType.Dispose();
      hv_Numbers.Dispose();
      hv_Message.Dispose();
      hv_Errors.Dispose();
      hv_Colors.Dispose();
      hv_NumWrong.Dispose();

      throw HDevExpDefaultException;
    }
  }

  public void extract_pill_types (HObject ho_Image, out HObject ho_Chambers, out HObject ho_ChambersUnion, 
      out HObject ho_Classes, out HTuple hv_PhiRef, out HTuple hv_RowRef, out HTuple hv_ColumnRef, 
      out HTuple hv_PillTypeCount)
  {



    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_Region, ho_ConnectedRegions, ho_SelectedRegions;
    HObject ho_Blister, ho_Rectangle=null, ho_Pattern, ho_PillType1;
    HObject ho_PillType2, ho_PillType3, ho_ImageReduced, ho_ImageR;
    HObject ho_ImageG, ho_ImageB, ho_ImageInvert, ho_RegionHysteresis2;
    HObject ho_RegionHysteresis3;

    // Local control variables 

    HTuple hv_I = new HTuple(), hv_Row = new HTuple();
    HTuple hv_J = new HTuple(), hv_Column = new HTuple(), hv_Area = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Chambers);
    HOperatorSet.GenEmptyObj(out ho_ChambersUnion);
    HOperatorSet.GenEmptyObj(out ho_Classes);
    HOperatorSet.GenEmptyObj(out ho_Region);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_Blister);
    HOperatorSet.GenEmptyObj(out ho_Rectangle);
    HOperatorSet.GenEmptyObj(out ho_Pattern);
    HOperatorSet.GenEmptyObj(out ho_PillType1);
    HOperatorSet.GenEmptyObj(out ho_PillType2);
    HOperatorSet.GenEmptyObj(out ho_PillType3);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_ImageR);
    HOperatorSet.GenEmptyObj(out ho_ImageG);
    HOperatorSet.GenEmptyObj(out ho_ImageB);
    HOperatorSet.GenEmptyObj(out ho_ImageInvert);
    HOperatorSet.GenEmptyObj(out ho_RegionHysteresis2);
    HOperatorSet.GenEmptyObj(out ho_RegionHysteresis3);
    hv_PhiRef = new HTuple();
    hv_RowRef = new HTuple();
    hv_ColumnRef = new HTuple();
    hv_PillTypeCount = new HTuple();
    try
    {
      ho_Region.Dispose();
      HOperatorSet.Threshold(ho_Image, out ho_Region, 90, 255);
      ho_ConnectedRegions.Dispose();
      HOperatorSet.Connection(ho_Region, out ho_ConnectedRegions);
      ho_SelectedRegions.Dispose();
      HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area", 
          "and", 5000, 999999);
      ho_Blister.Dispose();
      HOperatorSet.ShapeTrans(ho_SelectedRegions, out ho_Blister, "convex");
      ho_Chambers.Dispose();
      HOperatorSet.GenEmptyRegion(out ho_Chambers);
      for (hv_I=0; (int)hv_I<=4; hv_I = (int)hv_I + 1)
      {
        hv_Row.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_Row = 107+(hv_I*70);
        }
        for (hv_J=0; (int)hv_J<=2; hv_J = (int)hv_J + 1)
        {
          hv_Column.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_Column = 177+(hv_J*150);
          }
          ho_Rectangle.Dispose();
          HOperatorSet.GenRectangle2(out ho_Rectangle, hv_Row, hv_Column, 0, 64, 
              30);
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.ConcatObj(ho_Chambers, ho_Rectangle, out ExpTmpOutVar_0);
          ho_Chambers.Dispose();
          ho_Chambers = ExpTmpOutVar_0;
          }
        }
      }
      ho_Pattern.Dispose();
      HOperatorSet.Difference(ho_Blister, ho_Chambers, out ho_Pattern);
      ho_ChambersUnion.Dispose();
      HOperatorSet.Union1(ho_Chambers, out ho_ChambersUnion);
      hv_PhiRef.Dispose();
      HOperatorSet.OrientationRegion(ho_Blister, out hv_PhiRef);
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      {
      HTuple 
        ExpTmpLocalVar_PhiRef = ((new HTuple(180)).TupleRad()
          )+hv_PhiRef;
      hv_PhiRef.Dispose();
      hv_PhiRef = ExpTmpLocalVar_PhiRef;
      }
      }
      hv_Area.Dispose();hv_RowRef.Dispose();hv_ColumnRef.Dispose();
      HOperatorSet.AreaCenter(ho_Blister, out hv_Area, out hv_RowRef, out hv_ColumnRef);
      //
      //
      // +++ Extract pattern for classification +++
      ho_PillType1.Dispose();
      HOperatorSet.SelectShape(ho_Chambers, out ho_PillType1, "row", "and", 1, 145);
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.Union1(ho_PillType1, out ExpTmpOutVar_0);
      ho_PillType1.Dispose();
      ho_PillType1 = ExpTmpOutVar_0;
      }
      ho_PillType2.Dispose();
      HOperatorSet.SelectShape(ho_Chambers, out ho_PillType2, "row", "and", 145, 
          270);
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.Union1(ho_PillType2, out ExpTmpOutVar_0);
      ho_PillType2.Dispose();
      ho_PillType2 = ExpTmpOutVar_0;
      }
      ho_PillType3.Dispose();
      HOperatorSet.SelectShape(ho_Chambers, out ho_PillType3, "row", "and", 270, 
          390);
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.Union1(ho_PillType3, out ExpTmpOutVar_0);
      ho_PillType3.Dispose();
      ho_PillType3 = ExpTmpOutVar_0;
      }
      //
      //
      //Extract color space of yellow pills
      ho_ImageReduced.Dispose();
      HOperatorSet.ReduceDomain(ho_Image, ho_PillType1, out ho_ImageReduced);
      ho_ImageR.Dispose();ho_ImageG.Dispose();ho_ImageB.Dispose();
      HOperatorSet.Decompose3(ho_ImageReduced, out ho_ImageR, out ho_ImageG, out ho_ImageB
          );
      ho_Region.Dispose();
      HOperatorSet.Threshold(ho_ImageB, out ho_Region, 60, 95);
      //
      //Extract color space of red pills
      ho_ImageReduced.Dispose();
      HOperatorSet.ReduceDomain(ho_Image, ho_PillType2, out ho_ImageReduced);
      ho_ImageR.Dispose();ho_ImageG.Dispose();ho_ImageB.Dispose();
      HOperatorSet.Decompose3(ho_ImageReduced, out ho_ImageR, out ho_ImageG, out ho_ImageB
          );
      ho_ImageInvert.Dispose();
      HOperatorSet.InvertImage(ho_ImageB, out ho_ImageInvert);
      ho_RegionHysteresis2.Dispose();
      HOperatorSet.HysteresisThreshold(ho_ImageInvert, out ho_RegionHysteresis2, 
          190, 200, 5);
      //
      //Extract color space of green pills
      ho_ImageReduced.Dispose();
      HOperatorSet.ReduceDomain(ho_Image, ho_PillType3, out ho_ImageReduced);
      ho_ImageR.Dispose();ho_ImageG.Dispose();ho_ImageB.Dispose();
      HOperatorSet.Decompose3(ho_ImageReduced, out ho_ImageR, out ho_ImageG, out ho_ImageB
          );
      ho_ImageInvert.Dispose();
      HOperatorSet.InvertImage(ho_ImageB, out ho_ImageInvert);
      ho_RegionHysteresis3.Dispose();
      HOperatorSet.HysteresisThreshold(ho_ImageInvert, out ho_RegionHysteresis3, 
          180, 200, 10);
      //
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.Intersection(ho_Region, ho_PillType1, out ExpTmpOutVar_0);
      ho_PillType1.Dispose();
      ho_PillType1 = ExpTmpOutVar_0;
      }
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.Intersection(ho_RegionHysteresis2, ho_PillType2, out ExpTmpOutVar_0
          );
      ho_PillType2.Dispose();
      ho_PillType2 = ExpTmpOutVar_0;
      }
      hv_PillTypeCount.Dispose();
      hv_PillTypeCount = new HTuple();
      hv_PillTypeCount[0] = 3;
      hv_PillTypeCount[1] = 6;
      hv_PillTypeCount[2] = 6;
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.Intersection(ho_RegionHysteresis3, ho_PillType3, out ExpTmpOutVar_0
          );
      ho_PillType3.Dispose();
      ho_PillType3 = ExpTmpOutVar_0;
      }
      ho_Classes.Dispose();
      HOperatorSet.ConcatObj(ho_PillType1, ho_PillType2, out ho_Classes);
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.ConcatObj(ho_Classes, ho_PillType3, out ExpTmpOutVar_0);
      ho_Classes.Dispose();
      ho_Classes = ExpTmpOutVar_0;
      }
      ho_Region.Dispose();
      ho_ConnectedRegions.Dispose();
      ho_SelectedRegions.Dispose();
      ho_Blister.Dispose();
      ho_Rectangle.Dispose();
      ho_Pattern.Dispose();
      ho_PillType1.Dispose();
      ho_PillType2.Dispose();
      ho_PillType3.Dispose();
      ho_ImageReduced.Dispose();
      ho_ImageR.Dispose();
      ho_ImageG.Dispose();
      ho_ImageB.Dispose();
      ho_ImageInvert.Dispose();
      ho_RegionHysteresis2.Dispose();
      ho_RegionHysteresis3.Dispose();

      hv_I.Dispose();
      hv_Row.Dispose();
      hv_J.Dispose();
      hv_Column.Dispose();
      hv_Area.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_Region.Dispose();
      ho_ConnectedRegions.Dispose();
      ho_SelectedRegions.Dispose();
      ho_Blister.Dispose();
      ho_Rectangle.Dispose();
      ho_Pattern.Dispose();
      ho_PillType1.Dispose();
      ho_PillType2.Dispose();
      ho_PillType3.Dispose();
      ho_ImageReduced.Dispose();
      ho_ImageR.Dispose();
      ho_ImageG.Dispose();
      ho_ImageB.Dispose();
      ho_ImageInvert.Dispose();
      ho_RegionHysteresis2.Dispose();
      ho_RegionHysteresis3.Dispose();

      hv_I.Dispose();
      hv_Row.Dispose();
      hv_J.Dispose();
      hv_Column.Dispose();
      hv_Area.Dispose();

      throw HDevExpDefaultException;
    }
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_Image, ho_Chambers, ho_ChambersUnion;
    HObject ho_Classes, ho_Region=null, ho_ConnectedRegions=null;
    HObject ho_SelectedRegions=null, ho_RegionTrans=null, ho_ImageAffineTrans=null;
    HObject ho_ImageReduced=null, ho_ImageR=null, ho_ImageG=null;
    HObject ho_ImageB=null, ho_ClassRegions=null, ho_FinalClasses=null;
    HObject ho_ChambersRemaining=null, ho_PillsOfOneType=null;
    HObject ho_RegionDifference=null, ho_MissingPills=null;
    HObject ho_WrongPills=null, ho_WrongNumberOfPills=null;
    HObject ho_LeftOvers=null, ho_ObjectSelected=null;

    // Local control variables 

    HTuple hv_WindowHandle = new HTuple(), hv_PhiRef = new HTuple();
    HTuple hv_RowRef = new HTuple(), hv_ColumnRef = new HTuple();
    HTuple hv_PillTypeCount = new HTuple(), hv_NumClasses = new HTuple();
    HTuple hv_GMMHandle = new HTuple(), hv_Centers = new HTuple();
    HTuple hv_Iter = new HTuple(), hv_Count = new HTuple();
    HTuple hv_FileIndex = new HTuple(), hv_Phi = new HTuple();
    HTuple hv_Area1 = new HTuple(), hv_Row = new HTuple();
    HTuple hv_Column = new HTuple(), hv_HomMat2D = new HTuple();
    HTuple hv_Number = new HTuple(), hv_Index = new HTuple();
    HTuple hv_Area = new HTuple(), hv_Row1 = new HTuple();
    HTuple hv_Column1 = new HTuple(), hv_Mean = new HTuple();
    HTuple hv_Deviation = new HTuple(), hv_CountFinalClass = new HTuple();
    HTuple hv_Size = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_Chambers);
    HOperatorSet.GenEmptyObj(out ho_ChambersUnion);
    HOperatorSet.GenEmptyObj(out ho_Classes);
    HOperatorSet.GenEmptyObj(out ho_Region);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_RegionTrans);
    HOperatorSet.GenEmptyObj(out ho_ImageAffineTrans);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_ImageR);
    HOperatorSet.GenEmptyObj(out ho_ImageG);
    HOperatorSet.GenEmptyObj(out ho_ImageB);
    HOperatorSet.GenEmptyObj(out ho_ClassRegions);
    HOperatorSet.GenEmptyObj(out ho_FinalClasses);
    HOperatorSet.GenEmptyObj(out ho_ChambersRemaining);
    HOperatorSet.GenEmptyObj(out ho_PillsOfOneType);
    HOperatorSet.GenEmptyObj(out ho_RegionDifference);
    HOperatorSet.GenEmptyObj(out ho_MissingPills);
    HOperatorSet.GenEmptyObj(out ho_WrongPills);
    HOperatorSet.GenEmptyObj(out ho_WrongNumberOfPills);
    HOperatorSet.GenEmptyObj(out ho_LeftOvers);
    HOperatorSet.GenEmptyObj(out ho_ObjectSelected);
    try
    {
      //This example demonstrates an application from the pharmaceutical
      //industry. The task is to check the content of manually filled
      //blisters. The first image (reference) shows the combination, that
      //is requested. The subsequent images are then checked for this
      //setup drawn from the reference image. To perform this task we use
      //the gmm classifier, which will be trained with the reference image
      //in the beginning and is then used to classify the different pill
      //types in subsequent blister images.
      //
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.CloseWindow(HDevWindowStack.Pop());
      }
      ho_Image.Dispose();
      HOperatorSet.ReadImage(out ho_Image, "blister/blister_mixed_reference");
      hv_WindowHandle.Dispose();
      dev_open_window_fit_image(ho_Image, 0, 0, -1, -1, out hv_WindowHandle);
      set_display_font(hv_WindowHandle, 14, "mono", "true", "false");
      dev_update_off();
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.DispObj(ho_Image, HDevWindowStack.GetActive());
      }
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetDraw(HDevWindowStack.GetActive(), "margin");
      }
      //
      //First, we extract the content of the blister and pass
      //this information on to the gmm classifier
      disp_message(hv_WindowHandle, "Train gmm classifier on pill types", "window", 
          12, 12, "black", "true");
      ho_Chambers.Dispose();ho_ChambersUnion.Dispose();ho_Classes.Dispose();hv_PhiRef.Dispose();hv_RowRef.Dispose();hv_ColumnRef.Dispose();hv_PillTypeCount.Dispose();
      extract_pill_types(ho_Image, out ho_Chambers, out ho_ChambersUnion, out ho_Classes, 
          out hv_PhiRef, out hv_RowRef, out hv_ColumnRef, out hv_PillTypeCount);
      hv_NumClasses.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_NumClasses = new HTuple(hv_PillTypeCount.TupleLength()
          );
      }
      hv_GMMHandle.Dispose();
      HOperatorSet.CreateClassGmm(3, 3, (new HTuple(1)).TupleConcat(5), "spherical", 
          "normalization", 10, 42, out hv_GMMHandle);
      HOperatorSet.AddSamplesImageClassGmm(ho_Image, ho_Classes, hv_GMMHandle, 0);
      hv_Centers.Dispose();hv_Iter.Dispose();
      HOperatorSet.TrainClassGmm(hv_GMMHandle, 100, 0.001, "training", 0.0001, out hv_Centers, 
          out hv_Iter);
      //
      //
      //Then, the subsequent blisters are tested for their right combination
      hv_Count.Dispose();
      hv_Count = 12;
      HTuple end_val29 = hv_Count;
      HTuple step_val29 = 1;
      for (hv_FileIndex=1; hv_FileIndex.Continue(end_val29, step_val29); hv_FileIndex = hv_FileIndex.TupleAdd(step_val29))
      {
        //
        //Align image read
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        ho_Image.Dispose();
        HOperatorSet.ReadImage(out ho_Image, "blister/blister_mixed_"+(hv_FileIndex.TupleString(
            "02")));
        }
        ho_Region.Dispose();
        HOperatorSet.Threshold(ho_Image, out ho_Region, 90, 255);
        ho_ConnectedRegions.Dispose();
        HOperatorSet.Connection(ho_Region, out ho_ConnectedRegions);
        ho_SelectedRegions.Dispose();
        HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area", 
            "and", 5000, 9999999);
        ho_RegionTrans.Dispose();
        HOperatorSet.ShapeTrans(ho_SelectedRegions, out ho_RegionTrans, "convex");
        hv_Phi.Dispose();
        HOperatorSet.OrientationRegion(ho_RegionTrans, out hv_Phi);
        if ((int)(new HTuple(((hv_Phi.TupleAbs())).TupleGreater((new HTuple(90)).TupleRad()
            ))) != 0)
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_Phi = ((new HTuple(180)).TupleRad()
              )+hv_Phi;
          hv_Phi.Dispose();
          hv_Phi = ExpTmpLocalVar_Phi;
          }
          }
        }
        hv_Area1.Dispose();hv_Row.Dispose();hv_Column.Dispose();
        HOperatorSet.AreaCenter(ho_RegionTrans, out hv_Area1, out hv_Row, out hv_Column);
        hv_HomMat2D.Dispose();
        HOperatorSet.VectorAngleToRigid(hv_Row, hv_Column, hv_Phi, hv_RowRef, hv_ColumnRef, 
            hv_PhiRef, out hv_HomMat2D);
        ho_ImageAffineTrans.Dispose();
        HOperatorSet.AffineTransImage(ho_Image, out ho_ImageAffineTrans, hv_HomMat2D, 
            "constant", "false");
        ho_ImageReduced.Dispose();
        HOperatorSet.ReduceDomain(ho_ImageAffineTrans, ho_ChambersUnion, out ho_ImageReduced
            );
        ho_ImageR.Dispose();ho_ImageG.Dispose();ho_ImageB.Dispose();
        HOperatorSet.Decompose3(ho_ImageAffineTrans, out ho_ImageR, out ho_ImageG, 
            out ho_ImageB);
        //
        //Classify pill type for each chamber
        ho_ClassRegions.Dispose();
        HOperatorSet.ClassifyImageClassGmm(ho_ImageReduced, out ho_ClassRegions, 
            hv_GMMHandle, 0.0005);
        //
        hv_Number.Dispose();
        HOperatorSet.CountObj(ho_ClassRegions, out hv_Number);
        ho_FinalClasses.Dispose();
        HOperatorSet.GenEmptyObj(out ho_FinalClasses);
        ho_ChambersRemaining.Dispose();
        HOperatorSet.Connection(ho_Chambers, out ho_ChambersRemaining);
        HTuple end_val53 = 1;
        HTuple step_val53 = -1;
        for (hv_Index=hv_Number; hv_Index.Continue(end_val53, step_val53); hv_Index = hv_Index.TupleAdd(step_val53))
        {
          if (HDevWindowStack.IsOpen())
          {
            HOperatorSet.ClearWindow(HDevWindowStack.GetActive());
          }
          ho_Region.Dispose();
          HOperatorSet.SelectObj(ho_ClassRegions, out ho_Region, hv_Index);
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.Intersection(ho_ChambersRemaining, ho_Region, out ExpTmpOutVar_0
              );
          ho_Region.Dispose();
          ho_Region = ExpTmpOutVar_0;
          }
          ho_PillsOfOneType.Dispose();
          HOperatorSet.SelectShape(ho_Region, out ho_PillsOfOneType, (new HTuple("area")).TupleConcat(
              "width"), "and", (new HTuple(200)).TupleConcat(40), (new HTuple(3000)).TupleConcat(
              80));
          ho_RegionDifference.Dispose();
          HOperatorSet.Difference(ho_ChambersUnion, ho_PillsOfOneType, out ho_RegionDifference
              );
          ho_ConnectedRegions.Dispose();
          HOperatorSet.Connection(ho_RegionDifference, out ho_ConnectedRegions);
          ho_SelectedRegions.Dispose();
          HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area", 
              "and", 0, 7868);
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.ShapeTrans(ho_SelectedRegions, out ExpTmpOutVar_0, "convex");
          ho_SelectedRegions.Dispose();
          ho_SelectedRegions = ExpTmpOutVar_0;
          }
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.Union1(ho_SelectedRegions, out ExpTmpOutVar_0);
          ho_SelectedRegions.Dispose();
          ho_SelectedRegions = ExpTmpOutVar_0;
          }
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.Difference(ho_ChambersRemaining, ho_SelectedRegions, out ExpTmpOutVar_0
              );
          ho_ChambersRemaining.Dispose();
          ho_ChambersRemaining = ExpTmpOutVar_0;
          }
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.ConcatObj(ho_SelectedRegions, ho_FinalClasses, out ExpTmpOutVar_0
              );
          ho_FinalClasses.Dispose();
          ho_FinalClasses = ExpTmpOutVar_0;
          }
        }
        //
        //
        //Check for right combination
        ho_MissingPills.Dispose();
        HOperatorSet.GenEmptyObj(out ho_MissingPills);
        ho_WrongPills.Dispose();
        HOperatorSet.GenEmptyObj(out ho_WrongPills);
        ho_WrongNumberOfPills.Dispose();
        HOperatorSet.GenEmptyObj(out ho_WrongNumberOfPills);
        ho_LeftOvers.Dispose();
        HOperatorSet.Difference(ho_ChambersUnion, ho_FinalClasses, out ho_LeftOvers
            );
        hv_Area.Dispose();hv_Row1.Dispose();hv_Column1.Dispose();
        HOperatorSet.AreaCenter(ho_LeftOvers, out hv_Area, out hv_Row1, out hv_Column1);
        if ((int)(new HTuple(hv_Area.TupleGreater(0))) != 0)
        {
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.Connection(ho_LeftOvers, out ExpTmpOutVar_0);
          ho_LeftOvers.Dispose();
          ho_LeftOvers = ExpTmpOutVar_0;
          }
          hv_Number.Dispose();
          HOperatorSet.CountObj(ho_LeftOvers, out hv_Number);
          HTuple end_val77 = hv_Number;
          HTuple step_val77 = 1;
          for (hv_Index=1; hv_Index.Continue(end_val77, step_val77); hv_Index = hv_Index.TupleAdd(step_val77))
          {
            ho_ObjectSelected.Dispose();
            HOperatorSet.SelectObj(ho_LeftOvers, out ho_ObjectSelected, hv_Index);
            hv_Mean.Dispose();hv_Deviation.Dispose();
            HOperatorSet.Intensity(ho_ObjectSelected, ho_ImageB, out hv_Mean, out hv_Deviation);
            if ((int)(new HTuple(hv_Deviation.TupleGreater(40))) != 0)
            {
              {
              HObject ExpTmpOutVar_0;
              HOperatorSet.ConcatObj(ho_WrongPills, ho_ObjectSelected, out ExpTmpOutVar_0
                  );
              ho_WrongPills.Dispose();
              ho_WrongPills = ExpTmpOutVar_0;
              }
            }
            else
            {
              {
              HObject ExpTmpOutVar_0;
              HOperatorSet.ConcatObj(ho_MissingPills, ho_ObjectSelected, out ExpTmpOutVar_0
                  );
              ho_MissingPills.Dispose();
              ho_MissingPills = ExpTmpOutVar_0;
              }
            }
          }
        }
        //
        //Compute histogram
        hv_CountFinalClass.Dispose();
        hv_CountFinalClass = new HTuple();
        HTuple end_val90 = hv_NumClasses;
        HTuple step_val90 = 1;
        for (hv_Index=1; hv_Index.Continue(end_val90, step_val90); hv_Index = hv_Index.TupleAdd(step_val90))
        {
          ho_ObjectSelected.Dispose();
          HOperatorSet.SelectObj(ho_FinalClasses, out ho_ObjectSelected, hv_Index);
          {
          HObject ExpTmpOutVar_0;
          HOperatorSet.Connection(ho_ObjectSelected, out ExpTmpOutVar_0);
          ho_ObjectSelected.Dispose();
          ho_ObjectSelected = ExpTmpOutVar_0;
          }
          hv_Size.Dispose();
          HOperatorSet.CountObj(ho_ObjectSelected, out hv_Size);
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_CountFinalClass = hv_CountFinalClass.TupleConcat(
              hv_Size);
          hv_CountFinalClass.Dispose();
          hv_CountFinalClass = ExpTmpLocalVar_CountFinalClass;
          }
          }
        }
        //
        //Display classification results and output allover statistic
        display_results(ho_ImageAffineTrans, ho_LeftOvers, ho_FinalClasses, ho_WrongPills, 
            hv_CountFinalClass, hv_PillTypeCount, hv_WindowHandle);
        if ((int)(new HTuple(hv_FileIndex.TupleLess(hv_Count))) != 0)
        {
          disp_continue_message(hv_WindowHandle, "black", "true");
        }
        // stop(...); only in hdevelop
      }

    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_Image.Dispose();
      ho_Chambers.Dispose();
      ho_ChambersUnion.Dispose();
      ho_Classes.Dispose();
      ho_Region.Dispose();
      ho_ConnectedRegions.Dispose();
      ho_SelectedRegions.Dispose();
      ho_RegionTrans.Dispose();
      ho_ImageAffineTrans.Dispose();
      ho_ImageReduced.Dispose();
      ho_ImageR.Dispose();
      ho_ImageG.Dispose();
      ho_ImageB.Dispose();
      ho_ClassRegions.Dispose();
      ho_FinalClasses.Dispose();
      ho_ChambersRemaining.Dispose();
      ho_PillsOfOneType.Dispose();
      ho_RegionDifference.Dispose();
      ho_MissingPills.Dispose();
      ho_WrongPills.Dispose();
      ho_WrongNumberOfPills.Dispose();
      ho_LeftOvers.Dispose();
      ho_ObjectSelected.Dispose();

      hv_WindowHandle.Dispose();
      hv_PhiRef.Dispose();
      hv_RowRef.Dispose();
      hv_ColumnRef.Dispose();
      hv_PillTypeCount.Dispose();
      hv_NumClasses.Dispose();
      hv_GMMHandle.Dispose();
      hv_Centers.Dispose();
      hv_Iter.Dispose();
      hv_Count.Dispose();
      hv_FileIndex.Dispose();
      hv_Phi.Dispose();
      hv_Area1.Dispose();
      hv_Row.Dispose();
      hv_Column.Dispose();
      hv_HomMat2D.Dispose();
      hv_Number.Dispose();
      hv_Index.Dispose();
      hv_Area.Dispose();
      hv_Row1.Dispose();
      hv_Column1.Dispose();
      hv_Mean.Dispose();
      hv_Deviation.Dispose();
      hv_CountFinalClass.Dispose();
      hv_Size.Dispose();

      throw HDevExpDefaultException;
    }
    ho_Image.Dispose();
    ho_Chambers.Dispose();
    ho_ChambersUnion.Dispose();
    ho_Classes.Dispose();
    ho_Region.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_SelectedRegions.Dispose();
    ho_RegionTrans.Dispose();
    ho_ImageAffineTrans.Dispose();
    ho_ImageReduced.Dispose();
    ho_ImageR.Dispose();
    ho_ImageG.Dispose();
    ho_ImageB.Dispose();
    ho_ClassRegions.Dispose();
    ho_FinalClasses.Dispose();
    ho_ChambersRemaining.Dispose();
    ho_PillsOfOneType.Dispose();
    ho_RegionDifference.Dispose();
    ho_MissingPills.Dispose();
    ho_WrongPills.Dispose();
    ho_WrongNumberOfPills.Dispose();
    ho_LeftOvers.Dispose();
    ho_ObjectSelected.Dispose();

    hv_WindowHandle.Dispose();
    hv_PhiRef.Dispose();
    hv_RowRef.Dispose();
    hv_ColumnRef.Dispose();
    hv_PillTypeCount.Dispose();
    hv_NumClasses.Dispose();
    hv_GMMHandle.Dispose();
    hv_Centers.Dispose();
    hv_Iter.Dispose();
    hv_Count.Dispose();
    hv_FileIndex.Dispose();
    hv_Phi.Dispose();
    hv_Area1.Dispose();
    hv_Row.Dispose();
    hv_Column.Dispose();
    hv_HomMat2D.Dispose();
    hv_Number.Dispose();
    hv_Index.Dispose();
    hv_Area.Dispose();
    hv_Row1.Dispose();
    hv_Column1.Dispose();
    hv_Mean.Dispose();
    hv_Deviation.Dispose();
    hv_CountFinalClass.Dispose();
    hv_Size.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

} // end namespace

